### ISSUE TITLE
Release of your pre-train model?

### ISSUE THREAD

**Issue by zcfu1990** [ignaciohrdz/yolo-face-parts-detector#2]

**Comment by ignaciohm-legithealth** [comment]
I'm happy to see you find my work useful 😄 you can find the models in the [Releases](https://github.com/ignaciohrdz/yolo-face-parts-detector/releases) section

**Comment by ignaciohrdz** [comment]
I'm happy you found my work useful 😄 you can find the models in the [Releases](https://github.com/ignaciohrdz/yolo-face-parts-detector/releases) section
