### ISSUE TITLE
dectect.py and download_weights.py

### ISSUE THREAD

**Issue by EchoLymmm** [ignaciohrdz/yolo-face-parts-detector#3]
Could you please share your dectect.py and download_weights.py?

**Comment by ignaciohrdz** [comment]
Hi @lym-123-123 , I haven't implemented neither a `detect.py` nor a `download_weights.py` script, but you can easily create your own `detect.py` from my `live_demo.py` script. To get the weights, you can download the latest release from the **Releases** section.
